### ISSUE TITLE
Streamlit app not launching

### ISSUE THREAD

**Issue by Appel-flappen** [NoahHenrikKleinschmidt/qpcr-Analyser#1]
Streamlit app doesn't lauch after clicking on the link. I will try and run it myself of course later, but just wanted to let you know.
Streamlit initially says that app is booting, however eventually returns with an empty response: {}

**Comment by NoahHenrikKleinschmidt** [comment]
Hi there, 
Mhm, indeed, it seemed to be stuck on booting. I restarted it and I was now able to access it again. Seems to have been an issue on Streamlit's side. 
Let me know if you still have issues accessing the online version ✌️

**Comment by Appel-flappen** [comment]
@NoahHenrikKleinschmidt Great, thanks it now boots. unfortunately have some issues trying to use my data, will open another issue.
